
server:
  port:
    8080
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 200
      min-spare: 200

mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: org.example.bstest.demos.web.DTO   # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

spring:
  application:
    name: bishe
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      username: root
      password: root

  cache:
    type: caffeine
#    caffeine:
#      spec: maximumSize=20,expireAfterWrite=10s

# application.yml
management:
  server:
    port:8080

  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: "prometheus"
#        prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      sla:
        http:
          server:
            requests: 1ms,5ms,10ms,50ms,100ms,200ms,500ms,1s,5s
      percentiles-histogram:
        http:
          server:
            requests: true # 开启 http server 的请求监控



logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: error

